service_address = "127.0.0.1"
service_port = 8000

# Key from jwt.io
new_presentation_signing_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9
q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
-----END PUBLIC KEY-----
"""

# Corresponding private key
#
# -----BEGIN PRIVATE KEY-----
# MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgevZzL1gdAFr88hb2
# OF/2NxApJCzGCEDdfSp6VQO30hyhRANCAAQRWz+jn65BtOMvdyHKcvjBeBSDZH2r
# 1RTwjmYSi9R/zpBnuQ4EiMnCqfMPWiZqB4QdbAd0E7oH50VpuZ1P087G
# -----END PRIVATE KEY-----

test = """
# New presentation with id 5d313aea523d41569469e4abd72028d2
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0IiwicGlkIjoiNWQzMTNhZWE1MjNkNDE1Njk0NjllNGFiZDcyMDI4ZDIiLCJleHAiOjIwMDAwMDAwMDB9.IaL8xg_AF34oueaa5KxkplIC9AKJJ-D4OKuM-oLVwmpwyEGBKGxwa3wA6COHG5reyFPRlHpofsRPVVbtPZk6-A

# Sample authorization key
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpYDwCVZI5bUVgNOJR3lHTfO0oOQl
R+PbqML+RLVwjgHcaRJvi4R7GKvShFMp7KTj9FOdu/EHJrMoHNDSXUc3FA==
-----END PUBLIC KEY-----

# Corresponding private key for presentation viewers
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/YCN67i7pa4keOIP
tv1+3aRnUB5jcJEkm5Dnd0687aihRANCAASlgPAJVkjltRWA04lHeUdN87Sg5CVH
49uowv5EtXCOAdxpEm+LhHsYq9KEUynspOP0U5278Qcmsygc0NJdRzcU
-----END PRIVATE KEY-----

# Presenter JWT for presentation with id 5d313aea523d41569469e4abd72028d2
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVkMzEzYWVhNTIzZDQxNTY5NDY5ZTRhYmQ3MjAyOGQyIn0.eyJzdWIiOiJwcmVzZW50ZXIiLCJwaWQiOiI1ZDMxM2FlYTUyM2Q0MTU2OTQ2OWU0YWJkNzIwMjhkMiIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoyMDAwMDAwMDAwfQ.k3xCDeS-Y6IPVIzuyngzibHD2n66FmM4x4eY38PcjuDqzt8GYq2PLpBgXJlMae4jWjmGZfQoGbr8NYHFH_Q9SA

# User JWT for mitchell@confurious.io
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVkMzEzYWVhNTIzZDQxNTY5NDY5ZTRhYmQ3MjAyOGQyIn0.eyJzdWIiOiJtaXRjaGVsbEBjb25mdXJpb3VzLmlvIiwicGlkIjoiNWQzMTNhZWE1MjNkNDE1Njk0NjllNGFiZDcyMDI4ZDIiLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MjAwMDAwMDAwMH0._EMOpEFhQbmsvabx7m1kS72SNbTS7tdRquCz3ahi5Nd5O26K97hhl0P2RpxLnNbpS2oFYsM6QAse4cfK106DRQ

"""